<Project Sdk="Aspire.AppHost.Sdk/13.5.4">

	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
		<AspireUseCliBundle>true</AspireUseCliBundle>
		<UserSecretsId>69e81af9-4c97-469f-b86d-f40e78d04fba</UserSecretsId>
	</PropertyGroup>

	<ItemGroup>
		<ProjectReference Include="..\Demo.VatCalculator.Api\Demo.VatCalculator.Api.csproj" />
	</ItemGroup>


	<ItemGroup>
		<PackageReference Include="Aspire.Hosting.JavaScript" Version="13.5.3" />
	</ItemGroup>

</Project>
